#!/usr/bin/env ruby

require "fa-harness-tools"
require "optparse"

options = {}
OptionParser.new do |opts|
  opts.banner = "Usage: check-schedule [options]"
end.parse!

result = FaHarnessTools::CheckSchedule.new.verify?

if result.first
  puts result.last
  exit 0
else
  $stderr.puts result.last
  exit 1
end
