#!/usr/bin/env ruby

require "fa-harness-tools"
require "optparse"

options = {}
OptionParser.new do |opts|
  opts.banner = "Usage: check-schedule [options]"
end.parse!

result = FaHarnessTools::CheckSchedule.new.verify?

exit result ? 0 : 1
