#!/usr/bin/env ruby

require "fa-harness-tools"
require "optparse"

options = {
  github_owner: "fac",
  tag_prefix: nil,
  current_sha: nil
}
OptionParser.new do |opts|
  opts.banner = "Usage: check-forward-deploy [options]"

  opts.on("-b", "--build-no REVISION", "Build number/deployment revision") do |v|
    options[:build_no] = v
  end

  opts.on("-e", "--environment NAME", "Environment name") do |v|
    options[:environment] = v
  end

  opts.on("--github-owner NAME", "GitHub organisation/owner name, defaults to 'fac'") do |v|
    options[:github_owner] = v
  end

  opts.on("-r", "--repository NAME", "GitHub repository name") do |v|
    options[:repo] = v
  end

  opts.on("--tag-prefix PREFIX", "Git tag prefix, defaults to 'harness-deploy'") do |v|
    options[:tag_prefix] = v
  end

  opts.on("--current-sha SHA", "SHA currently deployed") do |v|
    options[:current_sha] = v
  end
end.parse!

client = FaHarnessTools::GithubClient.new(
  oauth_token: ENV.fetch("GITHUB_OAUTH_TOKEN"),
  owner: options.fetch(:github_owner),
  repo: options.fetch(:repo),
)
context = FaHarnessTools::HarnessContext.new(
  client: client,
  environment: options.fetch(:environment),
  build_no: options.fetch(:build_no),
)

result = FaHarnessTools::CheckForwardDeploy.new(
  client: client,
  context: context,
  tag_prefix: options.fetch(:tag_prefix, nil),
  current_sha: options.fetch(:current_sha, nil) 
).verify?

exit result ? 0 : 1
